// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: UIForm_Config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ConfigData {

  /// <summary>Holder for reflection information generated from UIForm_Config.proto</summary>
  public static partial class UIFormConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for UIForm_Config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UIFormConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNVSUZvcm1fQ29uZmlnLnByb3RvEgpDb25maWdEYXRhInsKDVVJRm9ybV9D",
            "b25maWcSCgoCaWQYASABKA0SEQoJYXNzZXROYW1lGAIgASgJEhMKC3VpR3Jv",
            "dXBOYW1lGAMgASgJEhoKEmFsbG93TXVsdGlJbnN0YW5jZRgEIAEoCBIaChJw",
            "YXVzZUNvdmVyZWRVSUZvcm0YBSABKAgiPgoSVUlGb3JtX0NvbmZpZ19EYXRh",
            "EigKBWl0ZW1zGAEgAygLMhkuQ29uZmlnRGF0YS5VSUZvcm1fQ29uZmlnQiAK",
            "HmNvbS5kZWVyLnNlcnZlci5wcm90b2J1Zi5wcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ConfigData.UIForm_Config), global::ConfigData.UIForm_Config.Parser, new[]{ "Id", "AssetName", "UiGroupName", "AllowMultiInstance", "PauseCoveredUIForm" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ConfigData.UIForm_Config_Data), global::ConfigData.UIForm_Config_Data.Parser, new[]{ "Items" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class UIForm_Config : pb::IMessage<UIForm_Config> {
    private static readonly pb::MessageParser<UIForm_Config> _parser = new pb::MessageParser<UIForm_Config>(() => new UIForm_Config());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UIForm_Config> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ConfigData.UIFormConfigReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UIForm_Config() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UIForm_Config(UIForm_Config other) : this() {
      id_ = other.id_;
      assetName_ = other.assetName_;
      uiGroupName_ = other.uiGroupName_;
      allowMultiInstance_ = other.allowMultiInstance_;
      pauseCoveredUIForm_ = other.pauseCoveredUIForm_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UIForm_Config Clone() {
      return new UIForm_Config(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private uint id_;
    /// <summary>
    ///* 唯一标识 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "assetName" field.</summary>
    public const int AssetNameFieldNumber = 2;
    private string assetName_ = "";
    /// <summary>
    ///* 资源名字 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AssetName {
      get { return assetName_; }
      set {
        assetName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "uiGroupName" field.</summary>
    public const int UiGroupNameFieldNumber = 3;
    private string uiGroupName_ = "";
    /// <summary>
    ///* 界面组名字 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UiGroupName {
      get { return uiGroupName_; }
      set {
        uiGroupName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "allowMultiInstance" field.</summary>
    public const int AllowMultiInstanceFieldNumber = 4;
    private bool allowMultiInstance_;
    /// <summary>
    ///* 是否允许多个界面实例 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool AllowMultiInstance {
      get { return allowMultiInstance_; }
      set {
        allowMultiInstance_ = value;
      }
    }

    /// <summary>Field number for the "pauseCoveredUIForm" field.</summary>
    public const int PauseCoveredUIFormFieldNumber = 5;
    private bool pauseCoveredUIForm_;
    /// <summary>
    ///* 是否暂停被其覆盖的界面 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool PauseCoveredUIForm {
      get { return pauseCoveredUIForm_; }
      set {
        pauseCoveredUIForm_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UIForm_Config);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UIForm_Config other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (AssetName != other.AssetName) return false;
      if (UiGroupName != other.UiGroupName) return false;
      if (AllowMultiInstance != other.AllowMultiInstance) return false;
      if (PauseCoveredUIForm != other.PauseCoveredUIForm) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (AssetName.Length != 0) hash ^= AssetName.GetHashCode();
      if (UiGroupName.Length != 0) hash ^= UiGroupName.GetHashCode();
      if (AllowMultiInstance != false) hash ^= AllowMultiInstance.GetHashCode();
      if (PauseCoveredUIForm != false) hash ^= PauseCoveredUIForm.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Id);
      }
      if (AssetName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AssetName);
      }
      if (UiGroupName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(UiGroupName);
      }
      if (AllowMultiInstance != false) {
        output.WriteRawTag(32);
        output.WriteBool(AllowMultiInstance);
      }
      if (PauseCoveredUIForm != false) {
        output.WriteRawTag(40);
        output.WriteBool(PauseCoveredUIForm);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
      }
      if (AssetName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AssetName);
      }
      if (UiGroupName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UiGroupName);
      }
      if (AllowMultiInstance != false) {
        size += 1 + 1;
      }
      if (PauseCoveredUIForm != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UIForm_Config other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.AssetName.Length != 0) {
        AssetName = other.AssetName;
      }
      if (other.UiGroupName.Length != 0) {
        UiGroupName = other.UiGroupName;
      }
      if (other.AllowMultiInstance != false) {
        AllowMultiInstance = other.AllowMultiInstance;
      }
      if (other.PauseCoveredUIForm != false) {
        PauseCoveredUIForm = other.PauseCoveredUIForm;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadUInt32();
            break;
          }
          case 18: {
            AssetName = input.ReadString();
            break;
          }
          case 26: {
            UiGroupName = input.ReadString();
            break;
          }
          case 32: {
            AllowMultiInstance = input.ReadBool();
            break;
          }
          case 40: {
            PauseCoveredUIForm = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class UIForm_Config_Data : pb::IMessage<UIForm_Config_Data> {
    private static readonly pb::MessageParser<UIForm_Config_Data> _parser = new pb::MessageParser<UIForm_Config_Data>(() => new UIForm_Config_Data());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UIForm_Config_Data> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ConfigData.UIFormConfigReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UIForm_Config_Data() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UIForm_Config_Data(UIForm_Config_Data other) : this() {
      items_ = other.items_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UIForm_Config_Data Clone() {
      return new UIForm_Config_Data(this);
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::ConfigData.UIForm_Config> _repeated_items_codec
        = pb::FieldCodec.ForMessage(10, global::ConfigData.UIForm_Config.Parser);
    private readonly pbc::RepeatedField<global::ConfigData.UIForm_Config> items_ = new pbc::RepeatedField<global::ConfigData.UIForm_Config>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ConfigData.UIForm_Config> Items {
      get { return items_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UIForm_Config_Data);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UIForm_Config_Data other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!items_.Equals(other.items_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= items_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      items_.WriteTo(output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += items_.CalculateSize(_repeated_items_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UIForm_Config_Data other) {
      if (other == null) {
        return;
      }
      items_.Add(other.items_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
