//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Error
{
public abstract partial class ErrorStyle :  Bright.Config.BeanBase 
{
    public ErrorStyle(ByteBuf _buf) 
    {
        PostInit();
    }

    public static ErrorStyle DeserializeErrorStyle(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case Error.ErrorStyleTip.__ID__: return new Error.ErrorStyleTip(_buf);
            case Error.ErrorStyleMsgbox.__ID__: return new Error.ErrorStyleMsgbox(_buf);
            case Error.ErrorStyleDlgOk.__ID__: return new Error.ErrorStyleDlgOk(_buf);
            case Error.ErrorStyleDlgOkCancel.__ID__: return new Error.ErrorStyleDlgOkCancel(_buf);
            default: throw new SerializationException();
        }
    }



    public virtual void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public virtual void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}