//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Error
{
public sealed partial class ErrorInfo :  Bright.Config.BeanBase 
{
    public ErrorInfo(ByteBuf _buf) 
    {
        Code = _buf.ReadString();
        Desc = _buf.ReadString();
        Style = Error.ErrorStyle.DeserializeErrorStyle(_buf);
        PostInit();
    }

    public static ErrorInfo DeserializeErrorInfo(ByteBuf _buf)
    {
        return new Error.ErrorInfo(_buf);
    }

    public string Code { get; private set; }
    public string Desc { get; private set; }
    public Error.ErrorStyle Style { get; private set; }

    public const int __ID__ = 392329776;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        Style?.Resolve(_tables);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        Style?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Code:" + Code + ","
        + "Desc:" + Desc + ","
        + "Style:" + Style + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}