//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Error
{
public sealed partial class ErrorStyleMsgbox :  Error.ErrorStyle 
{
    public ErrorStyleMsgbox(ByteBuf _buf)  : base(_buf) 
    {
        BtnName = _buf.ReadString();
        Operation = (Error.EOperation)_buf.ReadInt();
        PostInit();
    }

    public static ErrorStyleMsgbox DeserializeErrorStyleMsgbox(ByteBuf _buf)
    {
        return new Error.ErrorStyleMsgbox(_buf);
    }

    public string BtnName { get; private set; }
    public Error.EOperation Operation { get; private set; }

    public const int __ID__ = -1127190535;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "BtnName:" + BtnName + ","
        + "Operation:" + Operation + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}