//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Deer
{
public sealed partial class EntityData :  Bright.Config.BeanBase 
{
    public EntityData(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        EntityName = _buf.ReadString();
        AttackRange = _buf.ReadFloat();
        Cd = _buf.ReadFloat();
        MoveSpeed = _buf.ReadFloat();
        Damage = _buf.ReadFloat();
        HprBack = _buf.ReadFloat();
        BlueBack = _buf.ReadFloat();
        Good = _buf.ReadInt();
        Star = _buf.ReadInt();
        WeaponId = _buf.ReadInt();
        PostInit();
    }

    public static EntityData DeserializeEntityData(ByteBuf _buf)
    {
        return new Deer.EntityData(_buf);
    }

    /// <summary>
    /// 唯一标识
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 实体的名称
    /// </summary>
    public string EntityName { get; private set; }
    /// <summary>
    /// 攻击范围
    /// </summary>
    public float AttackRange { get; private set; }
    /// <summary>
    /// 冷却时间
    /// </summary>
    public float Cd { get; private set; }
    /// <summary>
    /// 移动速度
    /// </summary>
    public float MoveSpeed { get; private set; }
    /// <summary>
    /// 伤害值
    /// </summary>
    public float Damage { get; private set; }
    /// <summary>
    /// 回血
    /// </summary>
    public float HprBack { get; private set; }
    /// <summary>
    /// 回蓝
    /// </summary>
    public float BlueBack { get; private set; }
    /// <summary>
    /// 奖励金币
    /// </summary>
    public int Good { get; private set; }
    /// <summary>
    /// 奖励星星
    /// </summary>
    public int Star { get; private set; }
    /// <summary>
    /// 武器ID
    /// </summary>
    public int WeaponId { get; private set; }

    public const int __ID__ = 1628672813;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "EntityName:" + EntityName + ","
        + "AttackRange:" + AttackRange + ","
        + "Cd:" + Cd + ","
        + "MoveSpeed:" + MoveSpeed + ","
        + "Damage:" + Damage + ","
        + "HprBack:" + HprBack + ","
        + "BlueBack:" + BlueBack + ","
        + "Good:" + Good + ","
        + "Star:" + Star + ","
        + "WeaponId:" + WeaponId + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}