//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Deer
{
public sealed partial class Language_Config :  Bright.Config.BeanBase 
{
    public Language_Config(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        English = _buf.ReadString();
        Schinese = _buf.ReadString();
        PostInit();
    }

    public static Language_Config DeserializeLanguage_Config(ByteBuf _buf)
    {
        return new Deer.Language_Config(_buf);
    }

    /// <summary>
    /// 唯一标识
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 英文
    /// </summary>
    public string English { get; private set; }
    /// <summary>
    /// 简体中文
    /// </summary>
    public string Schinese { get; private set; }

    public const int __ID__ = -580972247;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "English:" + English + ","
        + "Schinese:" + Schinese + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}