//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Deer
{
public sealed partial class Sounds_Config :  Bright.Config.BeanBase 
{
    public Sounds_Config(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        GroupName = _buf.ReadString();
        SoundName = _buf.ReadString();
        SoundPriority = _buf.ReadString();
        SoundVolume = _buf.ReadFloat();
        Loop = _buf.ReadInt();
        SpatialBlend = _buf.ReadInt();
        Distance = _buf.ReadFloat();
        PostInit();
    }

    public static Sounds_Config DeserializeSounds_Config(ByteBuf _buf)
    {
        return new Deer.Sounds_Config(_buf);
    }

    /// <summary>
    /// 唯一标识
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 音效资源组
    /// </summary>
    public string GroupName { get; private set; }
    /// <summary>
    /// 音效名字
    /// </summary>
    public string SoundName { get; private set; }
    /// <summary>
    /// 音效优先级
    /// </summary>
    public string SoundPriority { get; private set; }
    /// <summary>
    /// 音量大小
    /// </summary>
    public float SoundVolume { get; private set; }
    /// <summary>
    /// 是否循环
    /// </summary>
    public int Loop { get; private set; }
    /// <summary>
    /// 空间混合
    /// </summary>
    public int SpatialBlend { get; private set; }
    /// <summary>
    /// 最大距离
    /// </summary>
    public float Distance { get; private set; }

    public const int __ID__ = -9582147;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "GroupName:" + GroupName + ","
        + "SoundName:" + SoundName + ","
        + "SoundPriority:" + SoundPriority + ","
        + "SoundVolume:" + SoundVolume + ","
        + "Loop:" + Loop + ","
        + "SpatialBlend:" + SpatialBlend + ","
        + "Distance:" + Distance + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}