//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Deer
{
   
public partial class TbUIData_Race
{
    private readonly Dictionary<int, Deer.UIData_Race> _dataMap;
    private readonly List<Deer.UIData_Race> _dataList;
    
    public TbUIData_Race(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, Deer.UIData_Race>();
        _dataList = new List<Deer.UIData_Race>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Deer.UIData_Race _v;
            _v = Deer.UIData_Race.DeserializeUIData_Race(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Deer.UIData_Race> DataMap => _dataMap;
    public List<Deer.UIData_Race> DataList => _dataList;

    public Deer.UIData_Race GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Deer.UIData_Race Get(int key) => _dataMap[key];
    public Deer.UIData_Race this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}