//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Deer
{
public sealed partial class UIData_GameMode :  Bright.Config.BeanBase 
{
    public UIData_GameMode(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Bg = _buf.ReadString();
        Icon = _buf.ReadString();
        Title = _buf.ReadString();
        GameIndex = _buf.ReadInt();
        PostInit();
    }

    public static UIData_GameMode DeserializeUIData_GameMode(ByteBuf _buf)
    {
        return new Deer.UIData_GameMode(_buf);
    }

    /// <summary>
    /// 唯一标识
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 背景图片
    /// </summary>
    public string Bg { get; private set; }
    /// <summary>
    /// 图标
    /// </summary>
    public string Icon { get; private set; }
    /// <summary>
    /// 标题
    /// </summary>
    public string Title { get; private set; }
    /// <summary>
    /// 游戏模式索引
    /// </summary>
    public int GameIndex { get; private set; }

    public const int __ID__ = -686637386;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Bg:" + Bg + ","
        + "Icon:" + Icon + ","
        + "Title:" + Title + ","
        + "GameIndex:" + GameIndex + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}