// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Heroes_Config.proto

package com.deer.server.protobuf.proto;

public final class HeroesConfig {
  private HeroesConfig() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Heroes_ConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConfigData.Heroes_Config)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     ** 唯一标识 
     * </pre>
     *
     * <code>uint32 id = 1;</code>
     */
    int getId();

    /**
     * <pre>
     ** 名字 
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     ** 名字 
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     ** 英雄id 
     * </pre>
     *
     * <code>uint32 hero_id = 3;</code>
     */
    int getHeroId();

    /**
     * <pre>
     ** 初始位置 
     * </pre>
     *
     * <code>repeated string init_position = 4;</code>
     */
    java.util.List<java.lang.String>
        getInitPositionList();
    /**
     * <pre>
     ** 初始位置 
     * </pre>
     *
     * <code>repeated string init_position = 4;</code>
     */
    int getInitPositionCount();
    /**
     * <pre>
     ** 初始位置 
     * </pre>
     *
     * <code>repeated string init_position = 4;</code>
     */
    java.lang.String getInitPosition(int index);
    /**
     * <pre>
     ** 初始位置 
     * </pre>
     *
     * <code>repeated string init_position = 4;</code>
     */
    com.google.protobuf.ByteString
        getInitPositionBytes(int index);

    /**
     * <pre>
     ** 预制体路径 
     * </pre>
     *
     * <code>string hero_prefab_path = 5;</code>
     */
    java.lang.String getHeroPrefabPath();
    /**
     * <pre>
     ** 预制体路径 
     * </pre>
     *
     * <code>string hero_prefab_path = 5;</code>
     */
    com.google.protobuf.ByteString
        getHeroPrefabPathBytes();
  }
  /**
   * Protobuf type {@code ConfigData.Heroes_Config}
   */
  public  static final class Heroes_Config extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConfigData.Heroes_Config)
      Heroes_ConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Heroes_Config.newBuilder() to construct.
    private Heroes_Config(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Heroes_Config() {
      id_ = 0;
      name_ = "";
      heroId_ = 0;
      initPosition_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      heroPrefabPath_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Heroes_Config(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              heroId_ = input.readUInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                initPosition_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              initPosition_.add(s);
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              heroPrefabPath_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          initPosition_ = initPosition_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.deer.server.protobuf.proto.HeroesConfig.internal_static_ConfigData_Heroes_Config_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.deer.server.protobuf.proto.HeroesConfig.internal_static_ConfigData_Heroes_Config_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config.class, com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     ** 唯一标识 
     * </pre>
     *
     * <code>uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     ** 名字 
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     ** 名字 
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HERO_ID_FIELD_NUMBER = 3;
    private int heroId_;
    /**
     * <pre>
     ** 英雄id 
     * </pre>
     *
     * <code>uint32 hero_id = 3;</code>
     */
    public int getHeroId() {
      return heroId_;
    }

    public static final int INIT_POSITION_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList initPosition_;
    /**
     * <pre>
     ** 初始位置 
     * </pre>
     *
     * <code>repeated string init_position = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getInitPositionList() {
      return initPosition_;
    }
    /**
     * <pre>
     ** 初始位置 
     * </pre>
     *
     * <code>repeated string init_position = 4;</code>
     */
    public int getInitPositionCount() {
      return initPosition_.size();
    }
    /**
     * <pre>
     ** 初始位置 
     * </pre>
     *
     * <code>repeated string init_position = 4;</code>
     */
    public java.lang.String getInitPosition(int index) {
      return initPosition_.get(index);
    }
    /**
     * <pre>
     ** 初始位置 
     * </pre>
     *
     * <code>repeated string init_position = 4;</code>
     */
    public com.google.protobuf.ByteString
        getInitPositionBytes(int index) {
      return initPosition_.getByteString(index);
    }

    public static final int HERO_PREFAB_PATH_FIELD_NUMBER = 5;
    private volatile java.lang.Object heroPrefabPath_;
    /**
     * <pre>
     ** 预制体路径 
     * </pre>
     *
     * <code>string hero_prefab_path = 5;</code>
     */
    public java.lang.String getHeroPrefabPath() {
      java.lang.Object ref = heroPrefabPath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        heroPrefabPath_ = s;
        return s;
      }
    }
    /**
     * <pre>
     ** 预制体路径 
     * </pre>
     *
     * <code>string hero_prefab_path = 5;</code>
     */
    public com.google.protobuf.ByteString
        getHeroPrefabPathBytes() {
      java.lang.Object ref = heroPrefabPath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        heroPrefabPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeUInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (heroId_ != 0) {
        output.writeUInt32(3, heroId_);
      }
      for (int i = 0; i < initPosition_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, initPosition_.getRaw(i));
      }
      if (!getHeroPrefabPathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, heroPrefabPath_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (heroId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, heroId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < initPosition_.size(); i++) {
          dataSize += computeStringSizeNoTag(initPosition_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getInitPositionList().size();
      }
      if (!getHeroPrefabPathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, heroPrefabPath_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config)) {
        return super.equals(obj);
      }
      com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config other = (com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && (getHeroId()
          == other.getHeroId());
      result = result && getInitPositionList()
          .equals(other.getInitPositionList());
      result = result && getHeroPrefabPath()
          .equals(other.getHeroPrefabPath());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + HERO_ID_FIELD_NUMBER;
      hash = (53 * hash) + getHeroId();
      if (getInitPositionCount() > 0) {
        hash = (37 * hash) + INIT_POSITION_FIELD_NUMBER;
        hash = (53 * hash) + getInitPositionList().hashCode();
      }
      hash = (37 * hash) + HERO_PREFAB_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getHeroPrefabPath().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConfigData.Heroes_Config}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConfigData.Heroes_Config)
        com.deer.server.protobuf.proto.HeroesConfig.Heroes_ConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.deer.server.protobuf.proto.HeroesConfig.internal_static_ConfigData_Heroes_Config_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.deer.server.protobuf.proto.HeroesConfig.internal_static_ConfigData_Heroes_Config_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config.class, com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config.Builder.class);
      }

      // Construct using com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        heroId_ = 0;

        initPosition_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        heroPrefabPath_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.deer.server.protobuf.proto.HeroesConfig.internal_static_ConfigData_Heroes_Config_descriptor;
      }

      @java.lang.Override
      public com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config getDefaultInstanceForType() {
        return com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config.getDefaultInstance();
      }

      @java.lang.Override
      public com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config build() {
        com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config buildPartial() {
        com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config result = new com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.name_ = name_;
        result.heroId_ = heroId_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          initPosition_ = initPosition_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.initPosition_ = initPosition_;
        result.heroPrefabPath_ = heroPrefabPath_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config) {
          return mergeFrom((com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config other) {
        if (other == com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getHeroId() != 0) {
          setHeroId(other.getHeroId());
        }
        if (!other.initPosition_.isEmpty()) {
          if (initPosition_.isEmpty()) {
            initPosition_ = other.initPosition_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureInitPositionIsMutable();
            initPosition_.addAll(other.initPosition_);
          }
          onChanged();
        }
        if (!other.getHeroPrefabPath().isEmpty()) {
          heroPrefabPath_ = other.heroPrefabPath_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <pre>
       ** 唯一标识 
       * </pre>
       *
       * <code>uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       ** 唯一标识 
       * </pre>
       *
       * <code>uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 唯一标识 
       * </pre>
       *
       * <code>uint32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       ** 名字 
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       ** 名字 
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       ** 名字 
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 名字 
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 名字 
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int heroId_ ;
      /**
       * <pre>
       ** 英雄id 
       * </pre>
       *
       * <code>uint32 hero_id = 3;</code>
       */
      public int getHeroId() {
        return heroId_;
      }
      /**
       * <pre>
       ** 英雄id 
       * </pre>
       *
       * <code>uint32 hero_id = 3;</code>
       */
      public Builder setHeroId(int value) {
        
        heroId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 英雄id 
       * </pre>
       *
       * <code>uint32 hero_id = 3;</code>
       */
      public Builder clearHeroId() {
        
        heroId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList initPosition_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureInitPositionIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          initPosition_ = new com.google.protobuf.LazyStringArrayList(initPosition_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <pre>
       ** 初始位置 
       * </pre>
       *
       * <code>repeated string init_position = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getInitPositionList() {
        return initPosition_.getUnmodifiableView();
      }
      /**
       * <pre>
       ** 初始位置 
       * </pre>
       *
       * <code>repeated string init_position = 4;</code>
       */
      public int getInitPositionCount() {
        return initPosition_.size();
      }
      /**
       * <pre>
       ** 初始位置 
       * </pre>
       *
       * <code>repeated string init_position = 4;</code>
       */
      public java.lang.String getInitPosition(int index) {
        return initPosition_.get(index);
      }
      /**
       * <pre>
       ** 初始位置 
       * </pre>
       *
       * <code>repeated string init_position = 4;</code>
       */
      public com.google.protobuf.ByteString
          getInitPositionBytes(int index) {
        return initPosition_.getByteString(index);
      }
      /**
       * <pre>
       ** 初始位置 
       * </pre>
       *
       * <code>repeated string init_position = 4;</code>
       */
      public Builder setInitPosition(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInitPositionIsMutable();
        initPosition_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 初始位置 
       * </pre>
       *
       * <code>repeated string init_position = 4;</code>
       */
      public Builder addInitPosition(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInitPositionIsMutable();
        initPosition_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 初始位置 
       * </pre>
       *
       * <code>repeated string init_position = 4;</code>
       */
      public Builder addAllInitPosition(
          java.lang.Iterable<java.lang.String> values) {
        ensureInitPositionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, initPosition_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 初始位置 
       * </pre>
       *
       * <code>repeated string init_position = 4;</code>
       */
      public Builder clearInitPosition() {
        initPosition_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 初始位置 
       * </pre>
       *
       * <code>repeated string init_position = 4;</code>
       */
      public Builder addInitPositionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureInitPositionIsMutable();
        initPosition_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object heroPrefabPath_ = "";
      /**
       * <pre>
       ** 预制体路径 
       * </pre>
       *
       * <code>string hero_prefab_path = 5;</code>
       */
      public java.lang.String getHeroPrefabPath() {
        java.lang.Object ref = heroPrefabPath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          heroPrefabPath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       ** 预制体路径 
       * </pre>
       *
       * <code>string hero_prefab_path = 5;</code>
       */
      public com.google.protobuf.ByteString
          getHeroPrefabPathBytes() {
        java.lang.Object ref = heroPrefabPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          heroPrefabPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       ** 预制体路径 
       * </pre>
       *
       * <code>string hero_prefab_path = 5;</code>
       */
      public Builder setHeroPrefabPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        heroPrefabPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 预制体路径 
       * </pre>
       *
       * <code>string hero_prefab_path = 5;</code>
       */
      public Builder clearHeroPrefabPath() {
        
        heroPrefabPath_ = getDefaultInstance().getHeroPrefabPath();
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 预制体路径 
       * </pre>
       *
       * <code>string hero_prefab_path = 5;</code>
       */
      public Builder setHeroPrefabPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        heroPrefabPath_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ConfigData.Heroes_Config)
    }

    // @@protoc_insertion_point(class_scope:ConfigData.Heroes_Config)
    private static final com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config();
    }

    public static com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Heroes_Config>
        PARSER = new com.google.protobuf.AbstractParser<Heroes_Config>() {
      @java.lang.Override
      public Heroes_Config parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Heroes_Config(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Heroes_Config> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Heroes_Config> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Heroes_Config_DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConfigData.Heroes_Config_Data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ConfigData.Heroes_Config items = 1;</code>
     */
    java.util.List<com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config> 
        getItemsList();
    /**
     * <code>repeated .ConfigData.Heroes_Config items = 1;</code>
     */
    com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config getItems(int index);
    /**
     * <code>repeated .ConfigData.Heroes_Config items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .ConfigData.Heroes_Config items = 1;</code>
     */
    java.util.List<? extends com.deer.server.protobuf.proto.HeroesConfig.Heroes_ConfigOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .ConfigData.Heroes_Config items = 1;</code>
     */
    com.deer.server.protobuf.proto.HeroesConfig.Heroes_ConfigOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ConfigData.Heroes_Config_Data}
   */
  public  static final class Heroes_Config_Data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConfigData.Heroes_Config_Data)
      Heroes_Config_DataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Heroes_Config_Data.newBuilder() to construct.
    private Heroes_Config_Data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Heroes_Config_Data() {
      items_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Heroes_Config_Data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                items_ = new java.util.ArrayList<com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config>();
                mutable_bitField0_ |= 0x00000001;
              }
              items_.add(
                  input.readMessage(com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.deer.server.protobuf.proto.HeroesConfig.internal_static_ConfigData_Heroes_Config_Data_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.deer.server.protobuf.proto.HeroesConfig.internal_static_ConfigData_Heroes_Config_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data.class, com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data.Builder.class);
    }

    public static final int ITEMS_FIELD_NUMBER = 1;
    private java.util.List<com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config> items_;
    /**
     * <code>repeated .ConfigData.Heroes_Config items = 1;</code>
     */
    public java.util.List<com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .ConfigData.Heroes_Config items = 1;</code>
     */
    public java.util.List<? extends com.deer.server.protobuf.proto.HeroesConfig.Heroes_ConfigOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .ConfigData.Heroes_Config items = 1;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .ConfigData.Heroes_Config items = 1;</code>
     */
    public com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .ConfigData.Heroes_Config items = 1;</code>
     */
    public com.deer.server.protobuf.proto.HeroesConfig.Heroes_ConfigOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(1, items_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, items_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data)) {
        return super.equals(obj);
      }
      com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data other = (com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data) obj;

      boolean result = true;
      result = result && getItemsList()
          .equals(other.getItemsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConfigData.Heroes_Config_Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConfigData.Heroes_Config_Data)
        com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.deer.server.protobuf.proto.HeroesConfig.internal_static_ConfigData_Heroes_Config_Data_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.deer.server.protobuf.proto.HeroesConfig.internal_static_ConfigData_Heroes_Config_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data.class, com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data.Builder.class);
      }

      // Construct using com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.deer.server.protobuf.proto.HeroesConfig.internal_static_ConfigData_Heroes_Config_Data_descriptor;
      }

      @java.lang.Override
      public com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data getDefaultInstanceForType() {
        return com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data.getDefaultInstance();
      }

      @java.lang.Override
      public com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data build() {
        com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data buildPartial() {
        com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data result = new com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data(this);
        int from_bitField0_ = bitField0_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data) {
          return mergeFrom((com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data other) {
        if (other == com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data.getDefaultInstance()) return this;
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = new java.util.ArrayList<com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config, com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config.Builder, com.deer.server.protobuf.proto.HeroesConfig.Heroes_ConfigOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .ConfigData.Heroes_Config items = 1;</code>
       */
      public java.util.List<com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ConfigData.Heroes_Config items = 1;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ConfigData.Heroes_Config items = 1;</code>
       */
      public com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ConfigData.Heroes_Config items = 1;</code>
       */
      public Builder setItems(
          int index, com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigData.Heroes_Config items = 1;</code>
       */
      public Builder setItems(
          int index, com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ConfigData.Heroes_Config items = 1;</code>
       */
      public Builder addItems(com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigData.Heroes_Config items = 1;</code>
       */
      public Builder addItems(
          int index, com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigData.Heroes_Config items = 1;</code>
       */
      public Builder addItems(
          com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ConfigData.Heroes_Config items = 1;</code>
       */
      public Builder addItems(
          int index, com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ConfigData.Heroes_Config items = 1;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigData.Heroes_Config items = 1;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ConfigData.Heroes_Config items = 1;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigData.Heroes_Config items = 1;</code>
       */
      public com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ConfigData.Heroes_Config items = 1;</code>
       */
      public com.deer.server.protobuf.proto.HeroesConfig.Heroes_ConfigOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ConfigData.Heroes_Config items = 1;</code>
       */
      public java.util.List<? extends com.deer.server.protobuf.proto.HeroesConfig.Heroes_ConfigOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .ConfigData.Heroes_Config items = 1;</code>
       */
      public com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config.getDefaultInstance());
      }
      /**
       * <code>repeated .ConfigData.Heroes_Config items = 1;</code>
       */
      public com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config.getDefaultInstance());
      }
      /**
       * <code>repeated .ConfigData.Heroes_Config items = 1;</code>
       */
      public java.util.List<com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config, com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config.Builder, com.deer.server.protobuf.proto.HeroesConfig.Heroes_ConfigOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config, com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config.Builder, com.deer.server.protobuf.proto.HeroesConfig.Heroes_ConfigOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ConfigData.Heroes_Config_Data)
    }

    // @@protoc_insertion_point(class_scope:ConfigData.Heroes_Config_Data)
    private static final com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data();
    }

    public static com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Heroes_Config_Data>
        PARSER = new com.google.protobuf.AbstractParser<Heroes_Config_Data>() {
      @java.lang.Override
      public Heroes_Config_Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Heroes_Config_Data(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Heroes_Config_Data> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Heroes_Config_Data> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.deer.server.protobuf.proto.HeroesConfig.Heroes_Config_Data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConfigData_Heroes_Config_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConfigData_Heroes_Config_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConfigData_Heroes_Config_Data_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConfigData_Heroes_Config_Data_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023Heroes_Config.proto\022\nConfigData\"k\n\rHer" +
      "oes_Config\022\n\n\002id\030\001 \001(\r\022\014\n\004name\030\002 \001(\t\022\017\n\007" +
      "hero_id\030\003 \001(\r\022\025\n\rinit_position\030\004 \003(\t\022\030\n\020" +
      "hero_prefab_path\030\005 \001(\t\">\n\022Heroes_Config_" +
      "Data\022(\n\005items\030\001 \003(\0132\031.ConfigData.Heroes_" +
      "ConfigB \n\036com.deer.server.protobuf.proto" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ConfigData_Heroes_Config_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ConfigData_Heroes_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConfigData_Heroes_Config_descriptor,
        new java.lang.String[] { "Id", "Name", "HeroId", "InitPosition", "HeroPrefabPath", });
    internal_static_ConfigData_Heroes_Config_Data_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ConfigData_Heroes_Config_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConfigData_Heroes_Config_Data_descriptor,
        new java.lang.String[] { "Items", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
