// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SceneScriptGroup_Config.proto

package com.deer.server.protobuf.proto;

public final class SceneScriptGroupConfig {
  private SceneScriptGroupConfig() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SceneScriptGroup_ConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConfigData.SceneScriptGroup_Config)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     ** 唯一标识 
     * </pre>
     *
     * <code>uint32 id = 1;</code>
     */
    int getId();

    /**
     * <pre>
     ** 表名 
     * </pre>
     *
     * <code>string script_name = 2;</code>
     */
    java.lang.String getScriptName();
    /**
     * <pre>
     ** 表名 
     * </pre>
     *
     * <code>string script_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getScriptNameBytes();

    /**
     * <pre>
     ** 说明 
     * </pre>
     *
     * <code>string remark = 3;</code>
     */
    java.lang.String getRemark();
    /**
     * <pre>
     ** 说明 
     * </pre>
     *
     * <code>string remark = 3;</code>
     */
    com.google.protobuf.ByteString
        getRemarkBytes();
  }
  /**
   * Protobuf type {@code ConfigData.SceneScriptGroup_Config}
   */
  public  static final class SceneScriptGroup_Config extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConfigData.SceneScriptGroup_Config)
      SceneScriptGroup_ConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SceneScriptGroup_Config.newBuilder() to construct.
    private SceneScriptGroup_Config(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SceneScriptGroup_Config() {
      id_ = 0;
      scriptName_ = "";
      remark_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SceneScriptGroup_Config(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              scriptName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              remark_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.deer.server.protobuf.proto.SceneScriptGroupConfig.internal_static_ConfigData_SceneScriptGroup_Config_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.deer.server.protobuf.proto.SceneScriptGroupConfig.internal_static_ConfigData_SceneScriptGroup_Config_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config.class, com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     ** 唯一标识 
     * </pre>
     *
     * <code>uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int SCRIPT_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object scriptName_;
    /**
     * <pre>
     ** 表名 
     * </pre>
     *
     * <code>string script_name = 2;</code>
     */
    public java.lang.String getScriptName() {
      java.lang.Object ref = scriptName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scriptName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     ** 表名 
     * </pre>
     *
     * <code>string script_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getScriptNameBytes() {
      java.lang.Object ref = scriptName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scriptName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REMARK_FIELD_NUMBER = 3;
    private volatile java.lang.Object remark_;
    /**
     * <pre>
     ** 说明 
     * </pre>
     *
     * <code>string remark = 3;</code>
     */
    public java.lang.String getRemark() {
      java.lang.Object ref = remark_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        remark_ = s;
        return s;
      }
    }
    /**
     * <pre>
     ** 说明 
     * </pre>
     *
     * <code>string remark = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRemarkBytes() {
      java.lang.Object ref = remark_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        remark_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeUInt32(1, id_);
      }
      if (!getScriptNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, scriptName_);
      }
      if (!getRemarkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, remark_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (!getScriptNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, scriptName_);
      }
      if (!getRemarkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, remark_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config)) {
        return super.equals(obj);
      }
      com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config other = (com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getScriptName()
          .equals(other.getScriptName());
      result = result && getRemark()
          .equals(other.getRemark());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + SCRIPT_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getScriptName().hashCode();
      hash = (37 * hash) + REMARK_FIELD_NUMBER;
      hash = (53 * hash) + getRemark().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConfigData.SceneScriptGroup_Config}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConfigData.SceneScriptGroup_Config)
        com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_ConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.deer.server.protobuf.proto.SceneScriptGroupConfig.internal_static_ConfigData_SceneScriptGroup_Config_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.deer.server.protobuf.proto.SceneScriptGroupConfig.internal_static_ConfigData_SceneScriptGroup_Config_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config.class, com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config.Builder.class);
      }

      // Construct using com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        scriptName_ = "";

        remark_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.deer.server.protobuf.proto.SceneScriptGroupConfig.internal_static_ConfigData_SceneScriptGroup_Config_descriptor;
      }

      @java.lang.Override
      public com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config getDefaultInstanceForType() {
        return com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config.getDefaultInstance();
      }

      @java.lang.Override
      public com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config build() {
        com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config buildPartial() {
        com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config result = new com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config(this);
        result.id_ = id_;
        result.scriptName_ = scriptName_;
        result.remark_ = remark_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config) {
          return mergeFrom((com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config other) {
        if (other == com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getScriptName().isEmpty()) {
          scriptName_ = other.scriptName_;
          onChanged();
        }
        if (!other.getRemark().isEmpty()) {
          remark_ = other.remark_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <pre>
       ** 唯一标识 
       * </pre>
       *
       * <code>uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       ** 唯一标识 
       * </pre>
       *
       * <code>uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 唯一标识 
       * </pre>
       *
       * <code>uint32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object scriptName_ = "";
      /**
       * <pre>
       ** 表名 
       * </pre>
       *
       * <code>string script_name = 2;</code>
       */
      public java.lang.String getScriptName() {
        java.lang.Object ref = scriptName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          scriptName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       ** 表名 
       * </pre>
       *
       * <code>string script_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getScriptNameBytes() {
        java.lang.Object ref = scriptName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          scriptName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       ** 表名 
       * </pre>
       *
       * <code>string script_name = 2;</code>
       */
      public Builder setScriptName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        scriptName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 表名 
       * </pre>
       *
       * <code>string script_name = 2;</code>
       */
      public Builder clearScriptName() {
        
        scriptName_ = getDefaultInstance().getScriptName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 表名 
       * </pre>
       *
       * <code>string script_name = 2;</code>
       */
      public Builder setScriptNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        scriptName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object remark_ = "";
      /**
       * <pre>
       ** 说明 
       * </pre>
       *
       * <code>string remark = 3;</code>
       */
      public java.lang.String getRemark() {
        java.lang.Object ref = remark_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          remark_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       ** 说明 
       * </pre>
       *
       * <code>string remark = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRemarkBytes() {
        java.lang.Object ref = remark_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          remark_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       ** 说明 
       * </pre>
       *
       * <code>string remark = 3;</code>
       */
      public Builder setRemark(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        remark_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 说明 
       * </pre>
       *
       * <code>string remark = 3;</code>
       */
      public Builder clearRemark() {
        
        remark_ = getDefaultInstance().getRemark();
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 说明 
       * </pre>
       *
       * <code>string remark = 3;</code>
       */
      public Builder setRemarkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        remark_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ConfigData.SceneScriptGroup_Config)
    }

    // @@protoc_insertion_point(class_scope:ConfigData.SceneScriptGroup_Config)
    private static final com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config();
    }

    public static com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SceneScriptGroup_Config>
        PARSER = new com.google.protobuf.AbstractParser<SceneScriptGroup_Config>() {
      @java.lang.Override
      public SceneScriptGroup_Config parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SceneScriptGroup_Config(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SceneScriptGroup_Config> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SceneScriptGroup_Config> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SceneScriptGroup_Config_DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConfigData.SceneScriptGroup_Config_Data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ConfigData.SceneScriptGroup_Config items = 1;</code>
     */
    java.util.List<com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config> 
        getItemsList();
    /**
     * <code>repeated .ConfigData.SceneScriptGroup_Config items = 1;</code>
     */
    com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config getItems(int index);
    /**
     * <code>repeated .ConfigData.SceneScriptGroup_Config items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .ConfigData.SceneScriptGroup_Config items = 1;</code>
     */
    java.util.List<? extends com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_ConfigOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .ConfigData.SceneScriptGroup_Config items = 1;</code>
     */
    com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_ConfigOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ConfigData.SceneScriptGroup_Config_Data}
   */
  public  static final class SceneScriptGroup_Config_Data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConfigData.SceneScriptGroup_Config_Data)
      SceneScriptGroup_Config_DataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SceneScriptGroup_Config_Data.newBuilder() to construct.
    private SceneScriptGroup_Config_Data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SceneScriptGroup_Config_Data() {
      items_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SceneScriptGroup_Config_Data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                items_ = new java.util.ArrayList<com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config>();
                mutable_bitField0_ |= 0x00000001;
              }
              items_.add(
                  input.readMessage(com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.deer.server.protobuf.proto.SceneScriptGroupConfig.internal_static_ConfigData_SceneScriptGroup_Config_Data_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.deer.server.protobuf.proto.SceneScriptGroupConfig.internal_static_ConfigData_SceneScriptGroup_Config_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data.class, com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data.Builder.class);
    }

    public static final int ITEMS_FIELD_NUMBER = 1;
    private java.util.List<com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config> items_;
    /**
     * <code>repeated .ConfigData.SceneScriptGroup_Config items = 1;</code>
     */
    public java.util.List<com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .ConfigData.SceneScriptGroup_Config items = 1;</code>
     */
    public java.util.List<? extends com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_ConfigOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .ConfigData.SceneScriptGroup_Config items = 1;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .ConfigData.SceneScriptGroup_Config items = 1;</code>
     */
    public com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .ConfigData.SceneScriptGroup_Config items = 1;</code>
     */
    public com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_ConfigOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(1, items_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, items_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data)) {
        return super.equals(obj);
      }
      com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data other = (com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data) obj;

      boolean result = true;
      result = result && getItemsList()
          .equals(other.getItemsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConfigData.SceneScriptGroup_Config_Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConfigData.SceneScriptGroup_Config_Data)
        com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.deer.server.protobuf.proto.SceneScriptGroupConfig.internal_static_ConfigData_SceneScriptGroup_Config_Data_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.deer.server.protobuf.proto.SceneScriptGroupConfig.internal_static_ConfigData_SceneScriptGroup_Config_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data.class, com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data.Builder.class);
      }

      // Construct using com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.deer.server.protobuf.proto.SceneScriptGroupConfig.internal_static_ConfigData_SceneScriptGroup_Config_Data_descriptor;
      }

      @java.lang.Override
      public com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data getDefaultInstanceForType() {
        return com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data.getDefaultInstance();
      }

      @java.lang.Override
      public com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data build() {
        com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data buildPartial() {
        com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data result = new com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data(this);
        int from_bitField0_ = bitField0_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data) {
          return mergeFrom((com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data other) {
        if (other == com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data.getDefaultInstance()) return this;
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = new java.util.ArrayList<com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config, com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config.Builder, com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_ConfigOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .ConfigData.SceneScriptGroup_Config items = 1;</code>
       */
      public java.util.List<com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ConfigData.SceneScriptGroup_Config items = 1;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ConfigData.SceneScriptGroup_Config items = 1;</code>
       */
      public com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ConfigData.SceneScriptGroup_Config items = 1;</code>
       */
      public Builder setItems(
          int index, com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigData.SceneScriptGroup_Config items = 1;</code>
       */
      public Builder setItems(
          int index, com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ConfigData.SceneScriptGroup_Config items = 1;</code>
       */
      public Builder addItems(com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigData.SceneScriptGroup_Config items = 1;</code>
       */
      public Builder addItems(
          int index, com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigData.SceneScriptGroup_Config items = 1;</code>
       */
      public Builder addItems(
          com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ConfigData.SceneScriptGroup_Config items = 1;</code>
       */
      public Builder addItems(
          int index, com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ConfigData.SceneScriptGroup_Config items = 1;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigData.SceneScriptGroup_Config items = 1;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ConfigData.SceneScriptGroup_Config items = 1;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ConfigData.SceneScriptGroup_Config items = 1;</code>
       */
      public com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ConfigData.SceneScriptGroup_Config items = 1;</code>
       */
      public com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_ConfigOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ConfigData.SceneScriptGroup_Config items = 1;</code>
       */
      public java.util.List<? extends com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_ConfigOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .ConfigData.SceneScriptGroup_Config items = 1;</code>
       */
      public com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config.getDefaultInstance());
      }
      /**
       * <code>repeated .ConfigData.SceneScriptGroup_Config items = 1;</code>
       */
      public com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config.getDefaultInstance());
      }
      /**
       * <code>repeated .ConfigData.SceneScriptGroup_Config items = 1;</code>
       */
      public java.util.List<com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config, com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config.Builder, com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_ConfigOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config, com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config.Builder, com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_ConfigOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ConfigData.SceneScriptGroup_Config_Data)
    }

    // @@protoc_insertion_point(class_scope:ConfigData.SceneScriptGroup_Config_Data)
    private static final com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data();
    }

    public static com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SceneScriptGroup_Config_Data>
        PARSER = new com.google.protobuf.AbstractParser<SceneScriptGroup_Config_Data>() {
      @java.lang.Override
      public SceneScriptGroup_Config_Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SceneScriptGroup_Config_Data(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SceneScriptGroup_Config_Data> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SceneScriptGroup_Config_Data> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.deer.server.protobuf.proto.SceneScriptGroupConfig.SceneScriptGroup_Config_Data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConfigData_SceneScriptGroup_Config_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConfigData_SceneScriptGroup_Config_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConfigData_SceneScriptGroup_Config_Data_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConfigData_SceneScriptGroup_Config_Data_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035SceneScriptGroup_Config.proto\022\nConfigD" +
      "ata\"J\n\027SceneScriptGroup_Config\022\n\n\002id\030\001 \001" +
      "(\r\022\023\n\013script_name\030\002 \001(\t\022\016\n\006remark\030\003 \001(\t\"" +
      "R\n\034SceneScriptGroup_Config_Data\0222\n\005items" +
      "\030\001 \003(\0132#.ConfigData.SceneScriptGroup_Con" +
      "figB \n\036com.deer.server.protobuf.protob\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ConfigData_SceneScriptGroup_Config_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ConfigData_SceneScriptGroup_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConfigData_SceneScriptGroup_Config_descriptor,
        new java.lang.String[] { "Id", "ScriptName", "Remark", });
    internal_static_ConfigData_SceneScriptGroup_Config_Data_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ConfigData_SceneScriptGroup_Config_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConfigData_SceneScriptGroup_Config_Data_descriptor,
        new java.lang.String[] { "Items", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
