# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Language_Config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Language_Config.proto',
  package='ConfigData',
  syntax='proto3',
  serialized_options=_b('\n\036com.deer.server.protobuf.proto'),
  serialized_pb=_b('\n\x15Language_Config.proto\x12\nConfigData\"@\n\x0fLanguage_Config\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0f\n\x07\x65nglish\x18\x03 \x01(\t\x12\x10\n\x08schinese\x18\x04 \x01(\t\"B\n\x14Language_Config_Data\x12*\n\x05items\x18\x01 \x03(\x0b\x32\x1b.ConfigData.Language_ConfigB \n\x1e\x63om.deer.server.protobuf.protob\x06proto3')
)




_LANGUAGE_CONFIG = _descriptor.Descriptor(
  name='Language_Config',
  full_name='ConfigData.Language_Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ConfigData.Language_Config.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='english', full_name='ConfigData.Language_Config.english', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='schinese', full_name='ConfigData.Language_Config.schinese', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=101,
)


_LANGUAGE_CONFIG_DATA = _descriptor.Descriptor(
  name='Language_Config_Data',
  full_name='ConfigData.Language_Config_Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='ConfigData.Language_Config_Data.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=169,
)

_LANGUAGE_CONFIG_DATA.fields_by_name['items'].message_type = _LANGUAGE_CONFIG
DESCRIPTOR.message_types_by_name['Language_Config'] = _LANGUAGE_CONFIG
DESCRIPTOR.message_types_by_name['Language_Config_Data'] = _LANGUAGE_CONFIG_DATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Language_Config = _reflection.GeneratedProtocolMessageType('Language_Config', (_message.Message,), dict(
  DESCRIPTOR = _LANGUAGE_CONFIG,
  __module__ = 'Language_Config_pb2'
  # @@protoc_insertion_point(class_scope:ConfigData.Language_Config)
  ))
_sym_db.RegisterMessage(Language_Config)

Language_Config_Data = _reflection.GeneratedProtocolMessageType('Language_Config_Data', (_message.Message,), dict(
  DESCRIPTOR = _LANGUAGE_CONFIG_DATA,
  __module__ = 'Language_Config_pb2'
  # @@protoc_insertion_point(class_scope:ConfigData.Language_Config_Data)
  ))
_sym_db.RegisterMessage(Language_Config_Data)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
